/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IERC1271Upgradeable } from "./IERC1271Upgradeable";
export type { IERC4626Upgradeable } from "./IERC4626Upgradeable";
