/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../../common";

export interface IInterpreterV1Interface extends utils.Interface {
  functions: {
    "eval(uint256,uint256[][])": FunctionFragment;
    "evalWithNamespace(uint256,uint256,uint256[][])": FunctionFragment;
    "functionPointers()": FunctionFragment;
    "stateChanges(uint256[])": FunctionFragment;
    "stateChangesWithNamespace(uint256,uint256[])": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "eval"
      | "evalWithNamespace"
      | "functionPointers"
      | "stateChanges"
      | "stateChangesWithNamespace"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "eval",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>[][]]
  ): string;
  encodeFunctionData(
    functionFragment: "evalWithNamespace",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>[][]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "functionPointers",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "stateChanges",
    values: [PromiseOrValue<BigNumberish>[]]
  ): string;
  encodeFunctionData(
    functionFragment: "stateChangesWithNamespace",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>[]]
  ): string;

  decodeFunctionResult(functionFragment: "eval", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "evalWithNamespace",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "functionPointers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "stateChanges",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "stateChangesWithNamespace",
    data: BytesLike
  ): Result;

  events: {};
}

export interface IInterpreterV1 extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IInterpreterV1Interface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    eval(
      dispatch: PromiseOrValue<BigNumberish>,
      context: PromiseOrValue<BigNumberish>[][],
      overrides?: CallOverrides
    ): Promise<
      [BigNumber[], BigNumber[]] & {
        stack: BigNumber[];
        stateChanges: BigNumber[];
      }
    >;

    evalWithNamespace(
      namespace: PromiseOrValue<BigNumberish>,
      dispatch: PromiseOrValue<BigNumberish>,
      context: PromiseOrValue<BigNumberish>[][],
      overrides?: CallOverrides
    ): Promise<
      [BigNumber[], BigNumber[]] & {
        stack: BigNumber[];
        stateChanges: BigNumber[];
      }
    >;

    functionPointers(overrides?: CallOverrides): Promise<[string]>;

    stateChanges(
      stateChanges: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    stateChangesWithNamespace(
      namespace: PromiseOrValue<BigNumberish>,
      stateChanges: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  eval(
    dispatch: PromiseOrValue<BigNumberish>,
    context: PromiseOrValue<BigNumberish>[][],
    overrides?: CallOverrides
  ): Promise<
    [BigNumber[], BigNumber[]] & {
      stack: BigNumber[];
      stateChanges: BigNumber[];
    }
  >;

  evalWithNamespace(
    namespace: PromiseOrValue<BigNumberish>,
    dispatch: PromiseOrValue<BigNumberish>,
    context: PromiseOrValue<BigNumberish>[][],
    overrides?: CallOverrides
  ): Promise<
    [BigNumber[], BigNumber[]] & {
      stack: BigNumber[];
      stateChanges: BigNumber[];
    }
  >;

  functionPointers(overrides?: CallOverrides): Promise<string>;

  stateChanges(
    stateChanges: PromiseOrValue<BigNumberish>[],
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  stateChangesWithNamespace(
    namespace: PromiseOrValue<BigNumberish>,
    stateChanges: PromiseOrValue<BigNumberish>[],
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    eval(
      dispatch: PromiseOrValue<BigNumberish>,
      context: PromiseOrValue<BigNumberish>[][],
      overrides?: CallOverrides
    ): Promise<
      [BigNumber[], BigNumber[]] & {
        stack: BigNumber[];
        stateChanges: BigNumber[];
      }
    >;

    evalWithNamespace(
      namespace: PromiseOrValue<BigNumberish>,
      dispatch: PromiseOrValue<BigNumberish>,
      context: PromiseOrValue<BigNumberish>[][],
      overrides?: CallOverrides
    ): Promise<
      [BigNumber[], BigNumber[]] & {
        stack: BigNumber[];
        stateChanges: BigNumber[];
      }
    >;

    functionPointers(overrides?: CallOverrides): Promise<string>;

    stateChanges(
      stateChanges: PromiseOrValue<BigNumberish>[],
      overrides?: CallOverrides
    ): Promise<void>;

    stateChangesWithNamespace(
      namespace: PromiseOrValue<BigNumberish>,
      stateChanges: PromiseOrValue<BigNumberish>[],
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    eval(
      dispatch: PromiseOrValue<BigNumberish>,
      context: PromiseOrValue<BigNumberish>[][],
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    evalWithNamespace(
      namespace: PromiseOrValue<BigNumberish>,
      dispatch: PromiseOrValue<BigNumberish>,
      context: PromiseOrValue<BigNumberish>[][],
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    functionPointers(overrides?: CallOverrides): Promise<BigNumber>;

    stateChanges(
      stateChanges: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    stateChangesWithNamespace(
      namespace: PromiseOrValue<BigNumberish>,
      stateChanges: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    eval(
      dispatch: PromiseOrValue<BigNumberish>,
      context: PromiseOrValue<BigNumberish>[][],
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    evalWithNamespace(
      namespace: PromiseOrValue<BigNumberish>,
      dispatch: PromiseOrValue<BigNumberish>,
      context: PromiseOrValue<BigNumberish>[][],
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    functionPointers(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    stateChanges(
      stateChanges: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    stateChangesWithNamespace(
      namespace: PromiseOrValue<BigNumberish>,
      stateChanges: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
