/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IInterpreterV1 } from "./IInterpreterV1";
export type { StandardInterpreter } from "./StandardInterpreter";
