/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IRainInterpreterIntegrity,
  IRainInterpreterIntegrityInterface,
} from "../../../../contracts/interpreter/deploy/IRainInterpreterIntegrity";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes[]",
        name: "sources",
        type: "bytes[]",
      },
      {
        internalType: "uint256",
        name: "constantsLength",
        type: "uint256",
      },
      {
        internalType: "uint256[]",
        name: "minStackOutputs",
        type: "uint256[]",
      },
    ],
    name: "ensureIntegrity",
    outputs: [
      {
        internalType: "uint256",
        name: "contextReads",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "stackLength",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IRainInterpreterIntegrity__factory {
  static readonly abi = _abi;
  static createInterface(): IRainInterpreterIntegrityInterface {
    return new utils.Interface(_abi) as IRainInterpreterIntegrityInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IRainInterpreterIntegrity {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as IRainInterpreterIntegrity;
  }
}
