/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../common";

export type CurationFeeConfigStruct = {
  token: PromiseOrValue<string>;
  amount: PromiseOrValue<BigNumberish>;
};

export type CurationFeeConfigStructOutput = [string, BigNumber] & {
  token: string;
  amount: BigNumber;
};

export type CurationTierConfigStruct = {
  tierContract: PromiseOrValue<string>;
  minimumTier: PromiseOrValue<BigNumberish>;
  context: PromiseOrValue<BigNumberish>[];
};

export type CurationTierConfigStructOutput = [
  string,
  BigNumber,
  BigNumber[]
] & { tierContract: string; minimumTier: BigNumber; context: BigNumber[] };

export type CurationConfigStruct = {
  factory: PromiseOrValue<string>;
  curator: PromiseOrValue<string>;
  feeConfig: CurationFeeConfigStruct;
  tierConfig: CurationTierConfigStruct;
};

export type CurationConfigStructOutput = [
  string,
  string,
  CurationFeeConfigStructOutput,
  CurationTierConfigStructOutput
] & {
  factory: string;
  curator: string;
  feeConfig: CurationFeeConfigStructOutput;
  tierConfig: CurationTierConfigStructOutput;
};

export interface FactoryCuratorInterface extends utils.Interface {
  functions: {
    "createChild(uint256,(address,address,(address,uint256),(address,uint256,uint256[])),bytes)": FunctionFragment;
    "registerConfig((address,address,(address,uint256),(address,uint256,uint256[])))": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic: "createChild" | "registerConfig"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "createChild",
    values: [
      PromiseOrValue<BigNumberish>,
      CurationConfigStruct,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "registerConfig",
    values: [CurationConfigStruct]
  ): string;

  decodeFunctionResult(
    functionFragment: "createChild",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerConfig",
    data: BytesLike
  ): Result;

  events: {
    "RegisterCuration(address,uint256,tuple)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "RegisterCuration"): EventFragment;
}

export interface RegisterCurationEventObject {
  sender: string;
  id: BigNumber;
  config: CurationConfigStructOutput;
}
export type RegisterCurationEvent = TypedEvent<
  [string, BigNumber, CurationConfigStructOutput],
  RegisterCurationEventObject
>;

export type RegisterCurationEventFilter =
  TypedEventFilter<RegisterCurationEvent>;

export interface FactoryCurator extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: FactoryCuratorInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    createChild(
      id_: PromiseOrValue<BigNumberish>,
      config_: CurationConfigStruct,
      createChild_: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    registerConfig(
      config_: CurationConfigStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  createChild(
    id_: PromiseOrValue<BigNumberish>,
    config_: CurationConfigStruct,
    createChild_: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  registerConfig(
    config_: CurationConfigStruct,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    createChild(
      id_: PromiseOrValue<BigNumberish>,
      config_: CurationConfigStruct,
      createChild_: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<string>;

    registerConfig(
      config_: CurationConfigStruct,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  filters: {
    "RegisterCuration(address,uint256,tuple)"(
      sender?: null,
      id?: null,
      config?: null
    ): RegisterCurationEventFilter;
    RegisterCuration(
      sender?: null,
      id?: null,
      config?: null
    ): RegisterCurationEventFilter;
  };

  estimateGas: {
    createChild(
      id_: PromiseOrValue<BigNumberish>,
      config_: CurationConfigStruct,
      createChild_: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    registerConfig(
      config_: CurationConfigStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    createChild(
      id_: PromiseOrValue<BigNumberish>,
      config_: CurationConfigStruct,
      createChild_: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    registerConfig(
      config_: CurationConfigStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
