/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IOrderBookV1,
  IOrderBookV1Interface,
} from "../../../contracts/orderbook/IOrderBookV1";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "owner",
        type: "address",
      },
      {
        internalType: "address",
        name: "token",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "id",
        type: "uint256",
      },
    ],
    name: "vaultBalance",
    outputs: [
      {
        internalType: "uint256",
        name: "balance",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IOrderBookV1__factory {
  static readonly abi = _abi;
  static createInterface(): IOrderBookV1Interface {
    return new utils.Interface(_abi) as IOrderBookV1Interface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IOrderBookV1 {
    return new Contract(address, _abi, signerOrProvider) as IOrderBookV1;
  }
}
