/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../../../../common";

export type StateConfigStruct = {
  sources: PromiseOrValue<BytesLike>[];
  constants: PromiseOrValue<BigNumberish>[];
};

export type StateConfigStructOutput = [string[], BigNumber[]] & {
  sources: string[];
  constants: BigNumber[];
};

export type InterpreterStateStruct = {
  stackBottom: PromiseOrValue<BigNumberish>;
  constantsBottom: PromiseOrValue<BigNumberish>;
  stateKV: PromiseOrValue<BigNumberish>;
  stateNamespace: PromiseOrValue<BigNumberish>;
  context: PromiseOrValue<BigNumberish>[][];
  compiledSources: PromiseOrValue<BytesLike>[];
};

export type InterpreterStateStructOutput = [
  BigNumber,
  BigNumber,
  BigNumber,
  BigNumber,
  BigNumber[][],
  string[]
] & {
  stackBottom: BigNumber;
  constantsBottom: BigNumber;
  stateKV: BigNumber;
  stateNamespace: BigNumber;
  context: BigNumber[][];
  compiledSources: string[];
};

export interface LibInterpreterStateTestInterface extends utils.Interface {
  functions: {
    "debug((bytes[],uint256[]),uint256[][],uint8,uint256,uint256[])": FunctionFragment;
    "eval((bytes[],uint256[]),uint256,uint256[])": FunctionFragment;
    "eval((bytes[],uint256[]),uint256[])": FunctionFragment;
    "evalStackTop((bytes[],uint256[]),uint256,uint256[])": FunctionFragment;
    "evalStackTop((bytes[],uint256[]),uint256[])": FunctionFragment;
    "serDeserialize((bytes[],uint256[]),uint256[][],uint256[])": FunctionFragment;
    "serialize((bytes[],uint256[]),uint256[])": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "debug"
      | "eval((bytes[],uint256[]),uint256,uint256[])"
      | "eval((bytes[],uint256[]),uint256[])"
      | "evalStackTop((bytes[],uint256[]),uint256,uint256[])"
      | "evalStackTop((bytes[],uint256[]),uint256[])"
      | "serDeserialize"
      | "serialize"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "debug",
    values: [
      StateConfigStruct,
      PromiseOrValue<BigNumberish>[][],
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>[]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "eval((bytes[],uint256[]),uint256,uint256[])",
    values: [
      StateConfigStruct,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>[]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "eval((bytes[],uint256[]),uint256[])",
    values: [StateConfigStruct, PromiseOrValue<BigNumberish>[]]
  ): string;
  encodeFunctionData(
    functionFragment: "evalStackTop((bytes[],uint256[]),uint256,uint256[])",
    values: [
      StateConfigStruct,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>[]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "evalStackTop((bytes[],uint256[]),uint256[])",
    values: [StateConfigStruct, PromiseOrValue<BigNumberish>[]]
  ): string;
  encodeFunctionData(
    functionFragment: "serDeserialize",
    values: [
      StateConfigStruct,
      PromiseOrValue<BigNumberish>[][],
      PromiseOrValue<BigNumberish>[]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "serialize",
    values: [StateConfigStruct, PromiseOrValue<BigNumberish>[]]
  ): string;

  decodeFunctionResult(functionFragment: "debug", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "eval((bytes[],uint256[]),uint256,uint256[])",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "eval((bytes[],uint256[]),uint256[])",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "evalStackTop((bytes[],uint256[]),uint256,uint256[])",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "evalStackTop((bytes[],uint256[]),uint256[])",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "serDeserialize",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "serialize", data: BytesLike): Result;

  events: {};
}

export interface LibInterpreterStateTest extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: LibInterpreterStateTestInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    debug(
      config_: StateConfigStruct,
      context_: PromiseOrValue<BigNumberish>[][],
      debugStyle_: PromiseOrValue<BigNumberish>,
      sourceIndex_: PromiseOrValue<BigNumberish>,
      minStackOutputs_: PromiseOrValue<BigNumberish>[],
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber] & {
        stackTop_: BigNumber;
        stackTopAfter_: BigNumber;
      }
    >;

    "eval((bytes[],uint256[]),uint256,uint256[])"(
      config_: StateConfigStruct,
      sourceIndex_: PromiseOrValue<BigNumberish>,
      minStackOutputs_: PromiseOrValue<BigNumberish>[],
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber] & {
        stackTopAfter_: BigNumber;
        stackBottom_: BigNumber;
      }
    >;

    "eval((bytes[],uint256[]),uint256[])"(
      config_: StateConfigStruct,
      minStackOutputs_: PromiseOrValue<BigNumberish>[],
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber] & {
        stackTopAfter_: BigNumber;
        stackBottom_: BigNumber;
      }
    >;

    "evalStackTop((bytes[],uint256[]),uint256,uint256[])"(
      config_: StateConfigStruct,
      sourceIndex_: PromiseOrValue<BigNumberish>,
      minStackOutputs_: PromiseOrValue<BigNumberish>[],
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber] & {
        stackTopAfter_: BigNumber;
        stackBottom_: BigNumber;
      }
    >;

    "evalStackTop((bytes[],uint256[]),uint256[])"(
      config_: StateConfigStruct,
      minStackOutputs_: PromiseOrValue<BigNumberish>[],
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber] & {
        stackTopAfter_: BigNumber;
        stackBottom_: BigNumber;
      }
    >;

    serDeserialize(
      config_: StateConfigStruct,
      context_: PromiseOrValue<BigNumberish>[][],
      minStackOutputs_: PromiseOrValue<BigNumberish>[],
      overrides?: CallOverrides
    ): Promise<
      [InterpreterStateStructOutput] & { state_: InterpreterStateStructOutput }
    >;

    serialize(
      config_: StateConfigStruct,
      minStackOutputs_: PromiseOrValue<BigNumberish>[],
      overrides?: CallOverrides
    ): Promise<[string] & { serialized_: string }>;
  };

  debug(
    config_: StateConfigStruct,
    context_: PromiseOrValue<BigNumberish>[][],
    debugStyle_: PromiseOrValue<BigNumberish>,
    sourceIndex_: PromiseOrValue<BigNumberish>,
    minStackOutputs_: PromiseOrValue<BigNumberish>[],
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber] & { stackTop_: BigNumber; stackTopAfter_: BigNumber }
  >;

  "eval((bytes[],uint256[]),uint256,uint256[])"(
    config_: StateConfigStruct,
    sourceIndex_: PromiseOrValue<BigNumberish>,
    minStackOutputs_: PromiseOrValue<BigNumberish>[],
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber] & {
      stackTopAfter_: BigNumber;
      stackBottom_: BigNumber;
    }
  >;

  "eval((bytes[],uint256[]),uint256[])"(
    config_: StateConfigStruct,
    minStackOutputs_: PromiseOrValue<BigNumberish>[],
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber] & {
      stackTopAfter_: BigNumber;
      stackBottom_: BigNumber;
    }
  >;

  "evalStackTop((bytes[],uint256[]),uint256,uint256[])"(
    config_: StateConfigStruct,
    sourceIndex_: PromiseOrValue<BigNumberish>,
    minStackOutputs_: PromiseOrValue<BigNumberish>[],
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber] & {
      stackTopAfter_: BigNumber;
      stackBottom_: BigNumber;
    }
  >;

  "evalStackTop((bytes[],uint256[]),uint256[])"(
    config_: StateConfigStruct,
    minStackOutputs_: PromiseOrValue<BigNumberish>[],
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber] & {
      stackTopAfter_: BigNumber;
      stackBottom_: BigNumber;
    }
  >;

  serDeserialize(
    config_: StateConfigStruct,
    context_: PromiseOrValue<BigNumberish>[][],
    minStackOutputs_: PromiseOrValue<BigNumberish>[],
    overrides?: CallOverrides
  ): Promise<InterpreterStateStructOutput>;

  serialize(
    config_: StateConfigStruct,
    minStackOutputs_: PromiseOrValue<BigNumberish>[],
    overrides?: CallOverrides
  ): Promise<string>;

  callStatic: {
    debug(
      config_: StateConfigStruct,
      context_: PromiseOrValue<BigNumberish>[][],
      debugStyle_: PromiseOrValue<BigNumberish>,
      sourceIndex_: PromiseOrValue<BigNumberish>,
      minStackOutputs_: PromiseOrValue<BigNumberish>[],
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber] & {
        stackTop_: BigNumber;
        stackTopAfter_: BigNumber;
      }
    >;

    "eval((bytes[],uint256[]),uint256,uint256[])"(
      config_: StateConfigStruct,
      sourceIndex_: PromiseOrValue<BigNumberish>,
      minStackOutputs_: PromiseOrValue<BigNumberish>[],
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber] & {
        stackTopAfter_: BigNumber;
        stackBottom_: BigNumber;
      }
    >;

    "eval((bytes[],uint256[]),uint256[])"(
      config_: StateConfigStruct,
      minStackOutputs_: PromiseOrValue<BigNumberish>[],
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber] & {
        stackTopAfter_: BigNumber;
        stackBottom_: BigNumber;
      }
    >;

    "evalStackTop((bytes[],uint256[]),uint256,uint256[])"(
      config_: StateConfigStruct,
      sourceIndex_: PromiseOrValue<BigNumberish>,
      minStackOutputs_: PromiseOrValue<BigNumberish>[],
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber] & {
        stackTopAfter_: BigNumber;
        stackBottom_: BigNumber;
      }
    >;

    "evalStackTop((bytes[],uint256[]),uint256[])"(
      config_: StateConfigStruct,
      minStackOutputs_: PromiseOrValue<BigNumberish>[],
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber] & {
        stackTopAfter_: BigNumber;
        stackBottom_: BigNumber;
      }
    >;

    serDeserialize(
      config_: StateConfigStruct,
      context_: PromiseOrValue<BigNumberish>[][],
      minStackOutputs_: PromiseOrValue<BigNumberish>[],
      overrides?: CallOverrides
    ): Promise<InterpreterStateStructOutput>;

    serialize(
      config_: StateConfigStruct,
      minStackOutputs_: PromiseOrValue<BigNumberish>[],
      overrides?: CallOverrides
    ): Promise<string>;
  };

  filters: {};

  estimateGas: {
    debug(
      config_: StateConfigStruct,
      context_: PromiseOrValue<BigNumberish>[][],
      debugStyle_: PromiseOrValue<BigNumberish>,
      sourceIndex_: PromiseOrValue<BigNumberish>,
      minStackOutputs_: PromiseOrValue<BigNumberish>[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "eval((bytes[],uint256[]),uint256,uint256[])"(
      config_: StateConfigStruct,
      sourceIndex_: PromiseOrValue<BigNumberish>,
      minStackOutputs_: PromiseOrValue<BigNumberish>[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "eval((bytes[],uint256[]),uint256[])"(
      config_: StateConfigStruct,
      minStackOutputs_: PromiseOrValue<BigNumberish>[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "evalStackTop((bytes[],uint256[]),uint256,uint256[])"(
      config_: StateConfigStruct,
      sourceIndex_: PromiseOrValue<BigNumberish>,
      minStackOutputs_: PromiseOrValue<BigNumberish>[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "evalStackTop((bytes[],uint256[]),uint256[])"(
      config_: StateConfigStruct,
      minStackOutputs_: PromiseOrValue<BigNumberish>[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    serDeserialize(
      config_: StateConfigStruct,
      context_: PromiseOrValue<BigNumberish>[][],
      minStackOutputs_: PromiseOrValue<BigNumberish>[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    serialize(
      config_: StateConfigStruct,
      minStackOutputs_: PromiseOrValue<BigNumberish>[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    debug(
      config_: StateConfigStruct,
      context_: PromiseOrValue<BigNumberish>[][],
      debugStyle_: PromiseOrValue<BigNumberish>,
      sourceIndex_: PromiseOrValue<BigNumberish>,
      minStackOutputs_: PromiseOrValue<BigNumberish>[],
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "eval((bytes[],uint256[]),uint256,uint256[])"(
      config_: StateConfigStruct,
      sourceIndex_: PromiseOrValue<BigNumberish>,
      minStackOutputs_: PromiseOrValue<BigNumberish>[],
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "eval((bytes[],uint256[]),uint256[])"(
      config_: StateConfigStruct,
      minStackOutputs_: PromiseOrValue<BigNumberish>[],
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "evalStackTop((bytes[],uint256[]),uint256,uint256[])"(
      config_: StateConfigStruct,
      sourceIndex_: PromiseOrValue<BigNumberish>,
      minStackOutputs_: PromiseOrValue<BigNumberish>[],
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "evalStackTop((bytes[],uint256[]),uint256[])"(
      config_: StateConfigStruct,
      minStackOutputs_: PromiseOrValue<BigNumberish>[],
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    serDeserialize(
      config_: StateConfigStruct,
      context_: PromiseOrValue<BigNumberish>[][],
      minStackOutputs_: PromiseOrValue<BigNumberish>[],
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    serialize(
      config_: StateConfigStruct,
      minStackOutputs_: PromiseOrValue<BigNumberish>[],
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
