/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../../../common";

export interface IInterpreterV1ConsumerInterface extends utils.Interface {
  functions: {
    "eval(address,uint256,uint256[][])": FunctionFragment;
    "evalWithNamespace(address,uint256,uint256,uint256[][])": FunctionFragment;
    "stack()": FunctionFragment;
    "stackTop()": FunctionFragment;
    "stateChanges()": FunctionFragment;
    "stateChanges(address,uint256[])": FunctionFragment;
    "stateChangesWithNamespace(address,uint256,uint256[])": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "eval"
      | "evalWithNamespace"
      | "stack"
      | "stackTop"
      | "stateChanges()"
      | "stateChanges(address,uint256[])"
      | "stateChangesWithNamespace"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "eval",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>[][]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "evalWithNamespace",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>[][]
    ]
  ): string;
  encodeFunctionData(functionFragment: "stack", values?: undefined): string;
  encodeFunctionData(functionFragment: "stackTop", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "stateChanges()",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "stateChanges(address,uint256[])",
    values: [PromiseOrValue<string>, PromiseOrValue<BigNumberish>[]]
  ): string;
  encodeFunctionData(
    functionFragment: "stateChangesWithNamespace",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>[]
    ]
  ): string;

  decodeFunctionResult(functionFragment: "eval", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "evalWithNamespace",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "stack", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "stackTop", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "stateChanges()",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "stateChanges(address,uint256[])",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "stateChangesWithNamespace",
    data: BytesLike
  ): Result;

  events: {};
}

export interface IInterpreterV1Consumer extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IInterpreterV1ConsumerInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    eval(
      interpreter_: PromiseOrValue<string>,
      dispatch_: PromiseOrValue<BigNumberish>,
      context_: PromiseOrValue<BigNumberish>[][],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    evalWithNamespace(
      interpreter_: PromiseOrValue<string>,
      namespace_: PromiseOrValue<BigNumberish>,
      dispatch_: PromiseOrValue<BigNumberish>,
      context_: PromiseOrValue<BigNumberish>[][],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    stack(overrides?: CallOverrides): Promise<[BigNumber[]]>;

    stackTop(overrides?: CallOverrides): Promise<[BigNumber]>;

    "stateChanges()"(overrides?: CallOverrides): Promise<[BigNumber[]]>;

    "stateChanges(address,uint256[])"(
      interpreter_: PromiseOrValue<string>,
      stateChanges_: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    stateChangesWithNamespace(
      interpreter_: PromiseOrValue<string>,
      namespace_: PromiseOrValue<BigNumberish>,
      stateChanges_: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  eval(
    interpreter_: PromiseOrValue<string>,
    dispatch_: PromiseOrValue<BigNumberish>,
    context_: PromiseOrValue<BigNumberish>[][],
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  evalWithNamespace(
    interpreter_: PromiseOrValue<string>,
    namespace_: PromiseOrValue<BigNumberish>,
    dispatch_: PromiseOrValue<BigNumberish>,
    context_: PromiseOrValue<BigNumberish>[][],
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  stack(overrides?: CallOverrides): Promise<BigNumber[]>;

  stackTop(overrides?: CallOverrides): Promise<BigNumber>;

  "stateChanges()"(overrides?: CallOverrides): Promise<BigNumber[]>;

  "stateChanges(address,uint256[])"(
    interpreter_: PromiseOrValue<string>,
    stateChanges_: PromiseOrValue<BigNumberish>[],
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  stateChangesWithNamespace(
    interpreter_: PromiseOrValue<string>,
    namespace_: PromiseOrValue<BigNumberish>,
    stateChanges_: PromiseOrValue<BigNumberish>[],
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    eval(
      interpreter_: PromiseOrValue<string>,
      dispatch_: PromiseOrValue<BigNumberish>,
      context_: PromiseOrValue<BigNumberish>[][],
      overrides?: CallOverrides
    ): Promise<void>;

    evalWithNamespace(
      interpreter_: PromiseOrValue<string>,
      namespace_: PromiseOrValue<BigNumberish>,
      dispatch_: PromiseOrValue<BigNumberish>,
      context_: PromiseOrValue<BigNumberish>[][],
      overrides?: CallOverrides
    ): Promise<void>;

    stack(overrides?: CallOverrides): Promise<BigNumber[]>;

    stackTop(overrides?: CallOverrides): Promise<BigNumber>;

    "stateChanges()"(overrides?: CallOverrides): Promise<BigNumber[]>;

    "stateChanges(address,uint256[])"(
      interpreter_: PromiseOrValue<string>,
      stateChanges_: PromiseOrValue<BigNumberish>[],
      overrides?: CallOverrides
    ): Promise<void>;

    stateChangesWithNamespace(
      interpreter_: PromiseOrValue<string>,
      namespace_: PromiseOrValue<BigNumberish>,
      stateChanges_: PromiseOrValue<BigNumberish>[],
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    eval(
      interpreter_: PromiseOrValue<string>,
      dispatch_: PromiseOrValue<BigNumberish>,
      context_: PromiseOrValue<BigNumberish>[][],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    evalWithNamespace(
      interpreter_: PromiseOrValue<string>,
      namespace_: PromiseOrValue<BigNumberish>,
      dispatch_: PromiseOrValue<BigNumberish>,
      context_: PromiseOrValue<BigNumberish>[][],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    stack(overrides?: CallOverrides): Promise<BigNumber>;

    stackTop(overrides?: CallOverrides): Promise<BigNumber>;

    "stateChanges()"(overrides?: CallOverrides): Promise<BigNumber>;

    "stateChanges(address,uint256[])"(
      interpreter_: PromiseOrValue<string>,
      stateChanges_: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    stateChangesWithNamespace(
      interpreter_: PromiseOrValue<string>,
      namespace_: PromiseOrValue<BigNumberish>,
      stateChanges_: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    eval(
      interpreter_: PromiseOrValue<string>,
      dispatch_: PromiseOrValue<BigNumberish>,
      context_: PromiseOrValue<BigNumberish>[][],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    evalWithNamespace(
      interpreter_: PromiseOrValue<string>,
      namespace_: PromiseOrValue<BigNumberish>,
      dispatch_: PromiseOrValue<BigNumberish>,
      context_: PromiseOrValue<BigNumberish>[][],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    stack(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    stackTop(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "stateChanges()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "stateChanges(address,uint256[])"(
      interpreter_: PromiseOrValue<string>,
      stateChanges_: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    stateChangesWithNamespace(
      interpreter_: PromiseOrValue<string>,
      namespace_: PromiseOrValue<BigNumberish>,
      stateChanges_: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
